### PR TITLE
Make configuration work in engines

### LINKED ISSUE #133: Cannot read property 'preferNative' of undefined
I am trying to replace ember-ajax with ember-fetch in an addon I use, but when I do it get the error:
`Cannot read property 'preferNative' of undefined`

content of error dump file can be seen below.
```=================================================================================

ENV Summary:

  TIME: Wed Oct 17 2018 12:56:02 GMT+0200 (Romance Daylight Time)
  TITLE: ember
  ARGV:
  - C:\Program Files\nodejs\node.exe
  - C:\Users\mmi\AppData\Roaming\npm\node_modules\ember-cli\bin\ember
  - build
  EXEC_PATH: C:\Program Files\nodejs\node.exe
  TMPDIR: C:\Users\mmi\AppData\Local\Temp
  SHELL: null
  PATH:
  - C
  - \Users\mmi\Desktop\Cmder_mini\bin;C
  - \Users\mmi\Desktop\Cmder_mini\vendor\conemu-maximus5\ConEmu\Scripts;C
  - \Users\mmi\Desktop\Cmder_mini\vendor\conemu-maximus5;C
  - \Users\mmi\Desktop\Cmder_mini\vendor\conemu-maximus5\ConEmu;C
  - \Program Files (x86)\Common Files\Oracle\Java\javapath;C
  - \Python27\;C
  - \Program Files (x86)\Intel\iCLS Client\;C
  - \Program Files\Intel\iCLS Client\;C
  - \WINDOWS\system32;C
  - \WINDOWS;C
  - \WINDOWS\System32\Wbem;C
  - \WINDOWS\System32\WindowsPowerShell\v1.0\;C
  - \Program Files (x86)\Microsoft SQL Server\80\Tools\Binn\;C
  - \Program Files\Microsoft SQL Server\90\DTS\Binn\;C
  - \Program Files\Microsoft SQL Server\90\Tools\binn\;C
  - \Program Files (x86)\Microsoft SQL Server\90\Tools\binn\;C
  - \Program Files (x86)\Microsoft SQL Server\90\DTS\Binn\;C
  - \Program Files (x86)\Microsoft SQL Server\90\Tools\Binn\VSShell\Common7\IDE\;C
  - \Program Files (x86)\Microsoft Visual Studio 8\Common7\IDE\PrivateAssemblies\;C
  - \Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C
  - \Program Files\Microsoft SQL Server\110\Tools\Binn\;C
  - \dev\Development\Tools\Nant\nant-0.92\bin;c
  - \Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C
  - \Program Files\Microsoft\Web Platform Installer\;C
  - \Program Files\Microsoft SQL Server\120\Tools\Binn\;C
  - \Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C
  - \Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C
  - \Program Files\Microsoft SQL Server\120\DTS\Binn\;C
  - \Program Files\Microsoft SQL Server\130\Tools\Binn\;C
  - \Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C
  - \Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C
  - \Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C
  - \Program Files\Intel\Intel(R) Management Engine Components\DAL;C
  - \Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C
  - \Program Files\Intel\Intel(R) Management Engine Components\IPT;C
  - \Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C
  - \Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C
  - \Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C
  - \Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C
  - \Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C
  - \Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C
  - \Program Files\dotnet\;C
  - \Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C
  - \Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C
  - \Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C
  - \Program Files\nodejs\;C
  - \WINDOWS\System32\OpenSSH\;C
  - \Program Files (x86)\Common Files\Acronis\VirtualFile\;C
  - \Program Files (x86)\Common Files\Acronis\VirtualFile64\;C
  - \Program Files (x86)\Common Files\Acronis\SnapAPI\;C
  - \Program Files\Git\cmd;C
  - \Program Files\TortoiseHg\;C
  - \Program Files (x86)\Yarn\bin\;C
  - \Users\mmi\.dnx\bin;C
  - \Users\mmi\AppData\Local\Microsoft\WindowsApps;C
  - \Program Files\Microsoft VS Code\bin;C
  - \Users\mmi\AppData\Local\GitHubDesktop\bin;C
  - \Users\mmi\AppData\Roaming\npm;C
  - \Users\mmi\AppData\Local\Microsoft\WindowsApps;C
  - \Users\mmi\AppData\Local\Programs\Microsoft VS Code\bin;C
  - \Users\mmi\AppData\Local\Yarn\bin;C
  - \Program Files\Git\usr\bin;C
  - \Program Files\Git\usr\share\vim\vim74;C
  - \Users\mmi\Desktop\Cmder_mini\
  PLATFORM: win32 x64
  FREEMEM: 4853907456
  TOTALMEM: 17080877056
  UPTIME: 571690.2593529
  LOADAVG: 0,0,0
  CPUS:
  - Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz - 3392
  - Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz - 3392
  - Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz - 3392
  - Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz - 3392
  - Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz - 3392
  - Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz - 3392
  - Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz - 3392
  - Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz - 3392
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - cldr: 31.0.1
  - http_parser: 2.7.0
  - icu: 59.1
  - modules: 57
  - nghttp2: 1.25.0
  - node: 8.9.1
  - openssl: 1.0.2m
  - tz: 2017b
  - unicode: 9.0
  - uv: 1.15.0
  - v8: 6.1.534.47
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Cannot read property 'preferNative' of undefined
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Cannot read property 'preferNative' of undefined
  - name: TypeError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError: Cannot read property 'preferNative' of undefined
    at Class.treeForVendor (C:\dev\GitHub\ember-cli-new-version\node_modules\ember-fetch\index.js:113:43)
    at Class._treeFor (C:\dev\GitHub\ember-cli-new-version\node_modules\ember-cli\lib\models\addon.js:616:33)
    at Class.treeFor (C:\dev\GitHub\ember-cli-new-version\node_modules\ember-cli\lib\models\addon.js:576:21)
    at addons.reduce (C:\dev\GitHub\ember-cli-new-version\node_modules\ember-cli\lib\models\addon.js:449:26)
    at Array.reduce (<anonymous>)
    at Class.eachAddonInvoke (C:\dev\GitHub\ember-cli-new-version\node_modules\ember-cli\lib\models\addon.js:446:24)
    at Class.treeFor (C:\dev\GitHub\ember-cli-new-version\node_modules\ember-cli\lib\models\addon.js:575:22)
    at project.addons.reduce (C:\dev\GitHub\ember-cli-new-version\node_modules\ember-cli\lib\broccoli\ember-app.js:699:26)
    at Array.reduce (<anonymous>)
    at EmberAddon._addonTreesFor (C:\dev\GitHub\ember-cli-new-version\node_modules\ember-cli\lib\broccoli\ember-app.js:697:32)

=================================================================================
```

You can check out this branch https://github.com/initram/ember-cli-new-version/tree/upgrade-no-jquery

Then run `yarn` and `ember build` to reproduce the error.

I tried to figure out what is going on my self, but I could not figure out if the addon that I am trying to change is doing something really weird that is causing the error or what.

### PR DESCRIPTION
**Pull request by mydea**
This makes sure that all nested dependencies use the correct application configuration, and that the import/configuration works in nested addons, especially in engines.

This fixes #133.

I tried it in an app of ours with engines & nested dependencies to ember-fetch, and this ensures that it always got the correct options passed.

Note: While investigating this, I also found out that it wasn't even taking the correct options for building. E.g. If, in my engines dummy app, I had `preferNative: true` specified in the `ember-cli-build.js`, it never actually got to this value, instead reading the config from ember-fetch's config (somehow? not entirely sure).

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -181,4 +166,22 @@ module.exports = {
...
+      // method in ember-cli.
+      // Keep iterating upward until we don't have a grandparent.
+      // Has to do this grandparent check because at some point we hit the project.
+      let app;
+      let current = this;
+      do {
+         app = current.app || this;
+      } while (current.parent && current.parent.parent && (current = current.parent));
+
+      return app;
```
Comment (nlfurniss) [inline index.js]: Since this functionality is in cli > 2.17 an this addon uses at least 3.5, seems like we can remove this?

Comment (nlfurniss) [reply index.js]: But given the current version of this addon tests against 3.5, we dont really support < 2.17...

File: index.js [hunk 2]
```diff
@@ -128,7 +112,8 @@ module.exports = {
       this.ui.writeWarnLine('[ember-fetch] Could not find `ember-cli-babel` addon, opting out of transpilation!')
     }
 
-    const preferNative = this.buildConfig.preferNative;
+    const app = this._findApp();
```
Comment (xg-wang) [inline index.js]: Can we store `app` as `this.app` to avoid calling `_findApp()` twice?

File: index.js (hunk 1 above)
Comment (xg-wang) [reply index.js]: We lack a way to test against different cli versions
https://github.com/tomdale/ember-cli-addon-tests/issues/25

File: index.js (hunk 2 above)
Comment (mydea) [reply index.js]: That it basically the whole issue that this PR is trying to fix: `this` is not the same in these different calls, at least not when run in an engine with nested dependencies.

I'm not sure how this is _supposed_ to work, but in my app with an engine, if I adjust the code like this:

```js
included() {
  this.__tid = Math.random();
  console.log('included', this.__tid);
  // ...
},
treeForVendor() {
  console.log('treeForVendor', this.__tid);
  // ...
}
```

I get this output:

```
included 0.47868310290718585
included 0.4535138056640218
treeForVendor undefined
treeForVendor undefined
```
(This is in my app with ember-cli 3.4)

**Comment by mydea** [comment]
I have rebased 👍

File: index.js (hunk 2 above)
Comment (xg-wang) [reply index.js]: Thanks for the explanation!
